Areas/Admin/Controllers/AdminSanphamController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShopPhone.Models;
using ShopPhone.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace ShopPhone.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminSanphamController : Controller
    {
        QLDienThoaiContext db = new QLDienThoaiContext();
        [Route("admin/create")]
        public IActionResult Index()
        {
            return View(db.Sanphams);
        }
        [Route("admin/GetSanPham")]
        public IActionResult GetSanPham()
        {
            return View(db.Sanphams);
        }
        [HttpGet]
        [Route("admin/create")]
        public IActionResult Create()
        {
            SpViewModel ds1 = new SpViewModel();
            return View(ds1);
        }
        [HttpPost]
        [Route("admin/create")]
        public IActionResult Create(Sanpham sp, IFormFile fileUpload)
        {
            
            if (fileUpload != null)
            {
                sp.MaSanPham = "SP" + db.Sanphams.Count() + 1;
                String filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileUpload.FileName);
                using (var file = new FileStream(filepath, FileMode.Create))
                {
                    fileUpload.CopyTo(file);
                }
                sp.Anh = fileUpload.FileName;
                Sanpham s = sp;
                db.Sanphams.Add(s);
                db.SaveChanges();
                //TempData["msgcreate"] = "<script>alert('Thêm sản phẩm thành công');</script>";
            }
            return RedirectToAction("GetSanPham", "Admin");
        }
        [HttpGet]
        [Route("admin/edit")]
        public IActionResult Edit(string id)
        {
            SpViewModel ds1 = new SpViewModel();
            ViewBag.ID = id;
            return View(ds1);
        }
        [HttpPost]
        [Route("admin/edit")]
        public IActionResult Edit(String id, Sanpham sp, IFormFile fileUpload)
        {
            if (fileUpload != null)
            {
                Sanpham sp1 = db.Sanphams.FirstOrDefault(p => p.MaSanPham.Equals(sp.MaSanPham));
                db.Sanphams.Remove(sp1);
                String filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileUpload.FileName);
                using (var file = new FileStream(filepath, FileMode.Create))
                {
                    fileUpload.CopyTo(file);
                }
                sp.Anh = fileUpload.FileName;
                Sanpham s = sp;
                db.Sanphams.Add(s);
                db.SaveChanges();
                TempData["msgcreate"] = "<script>alert('Sửa sản phẩm thành công');</script>";
            }
            return RedirectToAction("GetSanPham", "Admin");
        }
        public IActionResult Delete(string id)
        {
            var temp = db.Sanphams.FirstOrDefault(o => o.MaSanPham.Equals(id));
            if(temp != null)
            {
                db.Sanphams.Remove(temp);
                db.SaveChanges();
                TempData["msgdelete"] = "<script>alert('Xóa sản phẩm thành công');</script>";
                return RedirectToAction("GetSanPham", "Admin");
            }
            return Ok(404);
        }
    }
}

Areas/Admin/Views/AdminSanpham/Create.cshtml
@model ShopPhone.Areas.Admin.Models.SpViewModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Tables</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="index.html">Home</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Tables
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Thêm mới sản phẩm:</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <form action="Create" method="post" enctype="multipart/form-data">
                                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                            <div class="form-group">
                                                <label asp-for="sp.TenSanPham" class="control-label">Tên sản phẩm</label>
                                                <input asp-for="sp.TenSanPham" class="form-control" />
                                                <span asp-validation-for="sp.TenSanPham" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.Anh" class="control-label">Ảnh</label>
                                                <input type="file" asp-for="sp.Anh" class="form-control" name="fileUpload" />
                                                <span asp-validation-for="sp.Anh" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.MoTa" class="control-label">Mô tả</label>
                                                <input asp-for="sp.MoTa" class="form-control" />
                                                <span asp-validation-for="sp.MoTa" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.GiaTien" class="control-label">Giá tiền</label>
                                                <input asp-for="sp.GiaTien" class="form-control" />
                                                <span asp-validation-for="sp.GiaTien" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.SoLuong" class="control-label">Số lượng</label>
                                                <input asp-for="sp.SoLuong" class="form-control" />
                                                <span asp-validation-for="sp.SoLuong" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.MaDanhMuc" class="control-label">Hãng sản xuất</label>
                                                <select asp-for="sp.MaDanhMuc" class="form-control" asp-items="@Model.Danhmuc">
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" value="Create" class="btn btn-primary" @*href="@Url.Action("Create","Admin", new { Area="Admin"})"*@ />
                                            </div>
                                        </form>
                                    </div>
                                </div>

                                <div>
                                    <a asp-action="GetSanPham">Quay lại</a>
                                </div>
                                @Html.Raw(TempData["msgcreate"])
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminSanpham/Edit.cshtml
@model ShopPhone.Areas.Admin.Models.SpViewModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Tables</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="index.html">Home</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Tables
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Sửa thông tin sản phẩm:</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <form action="Edit" method="post" enctype="multipart/form-data">
                                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                            <div class="form-group">
                                                <label asp-for="sp.MaSanPham" class="control-label">Mã sản phẩm</label>
                                                <input asp-for="sp.MaSanPham" value="@ViewBag.ID" readonly="readonly" class="form-control" />
                                                <span asp-validation-for="sp.MaSanPham" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.TenSanPham" class="control-label">Tên sản phẩm</label>
                                                <input asp-for="sp.TenSanPham" value="@ViewBag.TenSanPham" class="form-control" />
                                                <span asp-validation-for="sp.TenSanPham" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.Anh" class="control-label">Ảnh</label>
                                                <input type="file" asp-for="sp.Anh" class="form-control" name="fileUpload" />
                                                <span asp-validation-for="sp.Anh" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.MoTa" class="control-label">Mô tả</label>
                                                <input asp-for="sp.MoTa" class="form-control" />
                                                <span asp-validation-for="sp.MoTa" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.GiaTien" class="control-label">Giá tiền</label>
                                                <input asp-for="sp.GiaTien" class="form-control" />
                                                <span asp-validation-for="sp.GiaTien" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.SoLuong" class="control-label">Số lượng</label>
                                                <input asp-for="sp.SoLuong" class="form-control" />
                                                <span asp-validation-for="sp.SoLuong" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="sp.MaDanhMuc" class="control-label">Hãng sản xuất</label>
                                                <select asp-for="sp.MaDanhMuc" class="form-control" asp-items="@Model.Danhmuc">
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" value="Edit" class="btn btn-primary" @*href="@Url.Action("Edit","Admin", new { Area="Admin" })"*@ />
                                            </div>
                                        </form>
                                    </div>
                                </div>

                                <div>
                                    <a asp-action="GetSanPham">Quay lại</a>
                                </div>
                                @Html.Raw(TempData["msgcreate"])
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminSanpham/GetSanPham.cshtml
@model IEnumerable<ShopPhone.Models.Sanpham>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Home";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Tables</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="index.html">Home</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Tables
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <p>
                                @Html.ActionLink("Thêm sản phẩm", "Create")
                            </p>
                            <h4 class="card-title">Danh sách sản phẩm:</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Mã sản phẩm</th>
                                                <th>Tên sản phẩm</th>
                                                <th>Mã hãng</th>
                                                <th>Ảnh</th>
                                                <th>Mô tả</th>
                                                <th>Số lượng</th>
                                                <th>Đơn giá</th>
                                                <th>Chức năng</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <th scope="row">@item.MaSanPham</th>
                                                    <td>@item.TenSanPham</td>
                                                    <td>@item.MaDanhMuc</td>
                                                    <td>
                                                        <img src="~/images/@item.Anh" height="50" width="50" />
                                                    </td>
                                                    <td>@item.MoTa</td>
                                                    <td>@item.SoLuong</td>
                                                    <td>@item.GiaTien</td>
                                                    <td>
                                                        <a asp-action="Edit" asp-controller="AdminSanpham" asp-area="Admin" asp-route-id="@item.MaSanPham">Edit</a> |
                                                        <a asp-action="Delete" asp-controller="AdminSanpham" asp-area="Admin" asp-route-id="@item.MaSanPham" >Delete</a>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            @Html.Raw(TempData["msgdelete"])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>