Areas/Admin/Controllers/AdminDonhangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopPhone.Models;

namespace ShopPhone.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminDonhangController : Controller
    {
        QLDienThoaiContext db = new QLDienThoaiContext();
        [Route("admin/GetDonhang")]
        public IActionResult GetDonhang()
        {
            return View(db.Donhangs);
        }
        public IActionResult Accept(string id)
        {
            Donhang dh = db.Donhangs.FirstOrDefault(p => p.MaDon.Equals(id));
            dh.TinhTrang = "Đã xử lý";
            db.SaveChanges();
            return RedirectToAction("GetDonhang", "Admin");
        }
        public IActionResult Delete(string id)
        {
            Donhang dh = db.Donhangs.FirstOrDefault(p => p.MaDon.Equals(id));
            db.Donhangs.Remove(dh);
            db.SaveChanges();
            return RedirectToAction("GetDonhang", "Admin");
        }
    }
}

Areas/Admin/Views/AdminDonhang/GetDonhang.cshtml
@model IEnumerable<ShopPhone.Models.Donhang>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Home";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="app-content content">
    <div class="content-wrapper">
        <div class="content-wrapper-before"></div>
        <div class="content-header row">
            <div class="content-header-left col-md-4 col-12 mb-2">
                <h3 class="content-header-title">Tables</h3>
            </div>
            <div class="content-header-right col-md-8 col-12">
                <div class="breadcrumbs-top float-md-right">
                    <div class="breadcrumb-wrapper mr-1">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="index.html">Home</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Tables
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Danh sách đơn hàng cần duyệt:</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collapse show">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Mã khách hàng</th>
                                                <th>Mã đơn hàng</th>
                                                <th>Ngày đặt</th>
                                                <th>Tình trạng</th>
                                                <th colspan="2" align="center">Chức năng</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <th scope="row">@item.MaKhachHang</th>
                                                    <td>@item.MaDon</td>
                                                    <td>@item.NgayDat</td>
                                                    <td>@item.TinhTrang</td>
                                                        <td>
                                                            <a asp-action="Accept" asp-controller="AdminDonhang" asp-area="Admin" asp-route-id="@item.MaDon">Duyệt đơn</a>
                                                        </td>
                                                        <td>
                                                            <a asp-action="Delete" asp-controller="AdminDonhang" asp-area="Admin" asp-route-id="@item.MaDon">Xóa đơn</a>
                                                        </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            @Html.Raw(TempData["msgdelete"])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>